# Generated by Django 5.2.1 on 2026-05-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notification', '0001_initial'),
        ('reports', '0001_initial'),
        ('users', '0004_user_e_signature_user_signatory_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.stockbook'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_notifications', to='users.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_notifications', to='users.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='wsi_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.wsireport'),
        ),
        migrations.AddField(
            model_name='notification',
            name='wsr_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.wsrreport'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('wsr_report', 'recipient'), name='unique_wsr_report_per_recipient'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('wsi_report', 'recipient'), name='unique_wsi_report_per_recipient'),
        ),
    ]
