# Generated by Django 5.2.13 on 2026-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_wsr_report_per_recipient',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_wsi_report_per_recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='snapshot_evaluation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='snapshot_stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
