# Generated by Django 5.2.13 on 2026-05-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_remove_notification_unique_wsr_report_per_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
