# Generated by Django 6.0.3 on 2026-04-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_recipient'),
        ('reports', '0002_wsi_reviewed_by_wsr_reviewed_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_notifications', to='users.user'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('wsr', 'recipient'), name='unique_wsr_per_user'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('wsi', 'recipient'), name='unique_wsi_per_user'),
        ),
    ]
