# Generated by Django 5.2.13 on 2026-04-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_submitted_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_wsr_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_wsi_per_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='wsi',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='wsr',
        ),
    ]
