# Generated by Django 5.2.13 on 2026-04-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_remove_notification_unique_wsr_per_user_and_more'),
        ('reports', '0005_remove_summary_wsi_remove_wsr_report_id_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.transaction'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('transaction', 'recipient'), name='unique_transaction_per_recipient'),
        ),
    ]
