# Generated by Django 5.2.13 on 2026-04-21 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notification_transaction_and_more'),
        ('reports', '0006_remove_transaction_evaluation_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_transaction_per_recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='transaction',
        ),
        migrations.AddField(
            model_name='notification',
            name='wsi_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.wsireport'),
        ),
        migrations.AddField(
            model_name='notification',
            name='wsr_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.wsrreport'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('wsr_report', 'recipient'), name='unique_wsr_report_per_recipient'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('wsi_report', 'recipient'), name='unique_wsi_report_per_recipient'),
        ),
    ]
