# Generated by Django 6.0.2 on 2026-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mI', models.CharField(max_length=1)),
                ('lname', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('WHCode', models.CharField(max_length=15)),
                ('Office_id', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('user_level', models.CharField(max_length=50)),
            ],
        ),
    ]
