# Generated by Django 6.0.2 on 2026-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('mI', models.CharField(blank=True, max_length=5)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_level', models.CharField(choices=[('Admin', 'Admin'), ('Warehouse Supervisor', 'Warehouse Supervisor')], max_length=50)),
                ('dept', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('WHCode', models.CharField(max_length=20)),
                ('Office_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
            ],
        ),
    ]
