# Generated by Django 5.2.13 on 2026-04-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Warehouse Supervisor', 'Warehouse Supervisor')], default='Warehouse Supervisor', max_length=50),
        ),
    ]
