# Generated by Django 5.2.1 on 2026-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='signatory_role',
            field=models.CharField(blank=True, choices=[('Asst. Branch Manager', 'Asst. Branch Manager'), ('Accountant 3', 'Accountant 3'), ('Branch Manager', 'Branch Manager')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Office_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='WHCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Warehouse Supervisor', 'Warehouse Supervisor'), ('Signatory', 'Signatory')], default='Warehouse Supervisor', max_length=50),
        ),
    ]
