# Generated by Django 6.0.2 on 2026-03-31 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBook',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('CerealType', models.CharField(blank=True, max_length=10, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Particulars', models.CharField(blank=True, max_length=100, null=True)),
                ('Plate_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('WTS', models.IntegerField(blank=True, null=True)),
                ('WSR', models.IntegerField(blank=True, null=True)),
                ('WSI', models.IntegerField(blank=True, null=True)),
                ('Batch_No', models.IntegerField(blank=True, null=True)),
                ('Age', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('AI_Number', models.IntegerField(blank=True, null=True)),
                ('OR_Number', models.IntegerField(blank=True, null=True)),
                ('Moisture_Content', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Classifier', models.CharField(blank=True, max_length=50, null=True)),
                ('Transaction', models.CharField(blank=True, max_length=20, null=True)),
                ('Pile_No', models.IntegerField(blank=True, null=True)),
                ('R_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('R_GKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('R_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cond_R', models.CharField(blank=True, max_length=5, null=True)),
                ('I_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('I_GKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('I_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cond_I', models.CharField(blank=True, max_length=5, null=True)),
                ('Fillers', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('B_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('B_GKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('B_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Assist_BM', models.CharField(blank=True, max_length=50, null=True)),
                ('Account_II', models.CharField(blank=True, max_length=50, null=True)),
                ('Branch_M', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockbooks', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='WSI',
            fields=[
                ('Issue_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Evaluation', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Report_id', models.ForeignKey(limit_choices_to={'WSI__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='wsi_issues', to='reports.stockbook')),
            ],
        ),
        migrations.CreateModel(
            name='WSR',
            fields=[
                ('Receipt_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Evaluation', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Report_id', models.ForeignKey(limit_choices_to={'WSR__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='wsr_receipts', to='reports.stockbook')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('Summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('E_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('E_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('WSI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='reports.wsi')),
                ('WSR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='reports.wsr')),
            ],
        ),
    ]
