# Generated by Django 5.2.1 on 2026-05-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_user_e_signature_user_signatory_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBook',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('CerealType', models.CharField(blank=True, max_length=10, null=True)),
                ('Status', models.CharField(choices=[('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
                ('Date', models.DateField(blank=True, null=True)),
                ('B_Bags', models.DecimalField(decimal_places=3, default=1000.0, max_digits=15)),
                ('B_GKG', models.DecimalField(decimal_places=3, default=1500000.0, max_digits=15)),
                ('B_NKG', models.DecimalField(decimal_places=3, default=2300000.0, max_digits=15)),
                ('Account_II', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_ii_stockbooks', to='users.user')),
                ('Assist_BM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assist_bm_stockbooks', to='users.user')),
                ('Branch_M', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_m_stockbooks', to='users.user')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockbooks', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_covered', models.DateField(blank=True, null=True)),
                ('CerealType', models.CharField(blank=True, max_length=10, null=True)),
                ('prev_B_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prev_B_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_R_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_R_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_I_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_I_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Condition', models.CharField(blank=True, max_length=5, null=True)),
                ('stockbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='reports.stockbook')),
            ],
        ),
        migrations.CreateModel(
            name='WSIReport',
            fields=[
                ('wsi_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('Evaluation', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('admin', 'Admin'), ('asst_bm', 'Asst. Branch Manager'), ('accountant', 'Accountant 3'), ('branch_m', 'Branch Manager'), ('done', 'Done')], default='admin', max_length=20)),
                ('admin_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('asst_bm_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('accountant_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('branch_m_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_wsi_reports', to='users.user')),
                ('stockbook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wsi_report', to='reports.stockbook')),
            ],
        ),
        migrations.CreateModel(
            name='WSRReport',
            fields=[
                ('wsr_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('Evaluation', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('current_stage', models.CharField(choices=[('admin', 'Admin'), ('asst_bm', 'Asst. Branch Manager'), ('accountant', 'Accountant 3'), ('branch_m', 'Branch Manager'), ('done', 'Done')], default='admin', max_length=20)),
                ('admin_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('asst_bm_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('accountant_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('branch_m_approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_wsr_reports', to='users.user')),
                ('stockbook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wsr_report', to='reports.stockbook')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WTS', 'WTS'), ('WSR', 'WSR'), ('WSI', 'WSI')], max_length=5)),
                ('Particulars', models.CharField(blank=True, max_length=100, null=True)),
                ('Plate_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Batch_No', models.CharField(blank=True, max_length=2, null=True)),
                ('AI_Number', models.CharField(blank=True, max_length=8, null=True)),
                ('OR_Number', models.CharField(blank=True, max_length=8, null=True)),
                ('Transaction_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('WTS_no', models.CharField(blank=True, max_length=8, null=True)),
                ('WSR_no', models.CharField(blank=True, max_length=8, null=True)),
                ('WSI_no', models.CharField(blank=True, max_length=8, null=True)),
                ('Age', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Moisture_Content', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Classifier', models.CharField(blank=True, max_length=50, null=True)),
                ('Pile_No', models.CharField(blank=True, max_length=10, null=True)),
                ('Fillers', models.CharField(blank=True, max_length=255, null=True)),
                ('R_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('R_GKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('R_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cond_R', models.CharField(blank=True, max_length=5, null=True)),
                ('I_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('I_GKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('I_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cond_I', models.CharField(blank=True, max_length=5, null=True)),
                ('stockbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reports.stockbook')),
                ('wsi_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reports.wsireport')),
                ('wsr_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reports.wsrreport')),
            ],
        ),
    ]
