# Generated by Django 6.0.2 on 2026-03-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBook',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('WHCode', models.CharField(max_length=20)),
                ('CerealType', models.CharField(max_length=10)),
                ('Status', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Prticulars', models.CharField(max_length=100)),
                ('Plate_Number', models.CharField(max_length=20)),
                ('WTS', models.IntegerField()),
                ('WRS', models.IntegerField()),
                ('WSI', models.IntegerField()),
                ('Batch_No', models.IntegerField()),
                ('Age', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AI_Number', models.IntegerField()),
                ('OR_Number', models.IntegerField()),
                ('Moisture_Content', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Classifier', models.CharField(max_length=50)),
                ('Transaction', models.CharField(max_length=20)),
                ('Pile_No', models.IntegerField()),
                ('R_Bags', models.DecimalField(decimal_places=2, max_digits=10)),
                ('R_GKG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('R_NKG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('I_Bags', models.DecimalField(decimal_places=2, max_digits=10)),
                ('I_GKG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('I_NKG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fillers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('B_Bags', models.DecimalField(decimal_places=2, max_digits=10)),
                ('B_GKG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('B_NKG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Assist_BM', models.CharField(max_length=50)),
                ('Account_II', models.CharField(max_length=50)),
                ('Branch_M', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockbooks', to='users.user')),
            ],
        ),
    ]
