# Generated by Django 5.2.13 on 2026-05-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbook',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockbook',
            name='Status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='In Progress', max_length=20),
        ),
    ]
