# Generated by Django 6.0.2 on 2026-03-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbook',
            old_name='Prticulars',
            new_name='Particulars',
        ),
    ]
