# Generated by Django 5.2.13 on 2026-05-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_stockbook_completed_at_alter_stockbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='stockbooks',
            field=models.ManyToManyField(blank=True, related_name='summary_groups', to='reports.stockbook'),
        ),
    ]
