# Generated by Django 6.0.3 on 2026-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_wsi_reviewed_by_wsr_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsi',
            name='Reason',
            field=models.TextField(default='-'),
        ),
    ]
