# Generated by Django 6.0.2 on 2026-03-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_prticulars_stockbook_particulars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbook',
            name='WHCode',
        ),
    ]
