# Generated by Django 6.0.3 on 2026-04-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_wsi_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsi',
            name='Reason',
            field=models.TextField(),
        ),
    ]
