# Generated by Django 5.2.13 on 2026-05-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_summary_stockbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='stockbooks',
        ),
    ]
