# Generated by Django 5.2.13 on 2026-04-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_remove_notification_unique_wsr_per_user_and_more'),
        ('reports', '0004_alter_wsi_reason'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='WSI',
        ),
        migrations.RemoveField(
            model_name='wsr',
            name='Report_id',
        ),
        migrations.RemoveField(
            model_name='wsr',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='WSR',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='E_Bags',
            new_name='prev_B_Bags',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='E_NKG',
            new_name='prev_B_NKG',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='Summary_id',
            new_name='summary_id',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='AI_Number',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Batch_No',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Classifier',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Cond_I',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Cond_R',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Fillers',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='I_Bags',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='I_GKG',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='I_NKG',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Moisture_Content',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='OR_Number',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Particulars',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Pile_No',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Plate_Number',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='R_Bags',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='R_GKG',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='R_NKG',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='WSI',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='WSR',
        ),
        migrations.RemoveField(
            model_name='stockbook',
            name='WTS',
        ),
        migrations.AddField(
            model_name='summary',
            name='CerealType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='Condition',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='date_covered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='stockbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='reports.stockbook'),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_I_Bags',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_I_NKG',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_R_Bags',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='summary',
            name='total_R_NKG',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockbook',
            name='Status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WTS', 'WTS'), ('WSR', 'WSR'), ('WSI', 'WSI')], max_length=5)),
                ('Evaluation', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Particulars', models.CharField(blank=True, max_length=100, null=True)),
                ('Plate_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Batch_No', models.IntegerField(blank=True, null=True)),
                ('AI_Number', models.IntegerField(blank=True, null=True)),
                ('OR_Number', models.IntegerField(blank=True, null=True)),
                ('Transaction_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('WTS_no', models.IntegerField(blank=True, null=True)),
                ('WSR_no', models.IntegerField(blank=True, null=True)),
                ('WSI_no', models.IntegerField(blank=True, null=True)),
                ('Age', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Moisture_Content', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Classifier', models.CharField(blank=True, max_length=50, null=True)),
                ('Pile_No', models.IntegerField(blank=True, null=True)),
                ('Fillers', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('R_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('R_GKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('R_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cond_R', models.CharField(blank=True, max_length=5, null=True)),
                ('I_Bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('I_GKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('I_NKG', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cond_I', models.CharField(blank=True, max_length=5, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transactions', to='users.user')),
                ('stockbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='reports.stockbook')),
            ],
        ),
        migrations.DeleteModel(
            name='WSI',
        ),
        migrations.DeleteModel(
            name='WSR',
        ),
    ]
