# Generated by Django 6.0.2 on 2026-03-28 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_stockbook_ai_number_alter_stockbook_account_ii_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WRS',
            fields=[
                ('Receipt_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Evaluation', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('CerealType', models.ForeignKey(blank=True, db_column='CerealType_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrs_cereal', to='reports.stockbook')),
                ('Report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrs_receipts', to='reports.stockbook')),
            ],
        ),
    ]
