# Generated by Django 6.0.2 on 2026-03-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_wrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrs',
            name='CerealType',
        ),
    ]
