# Generated by Django 5.2.13 on 2026-05-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_summary_prev_b_bags_alter_summary_prev_b_nkg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='stockbook',
        ),
        migrations.AddField(
            model_name='summary',
            name='stockbooks',
            field=models.ManyToManyField(blank=True, related_name='summaries', to='reports.stockbook'),
        ),
    ]
