# Generated by Django 6.0.2 on 2026-03-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_wrs_cerealtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSI',
            fields=[
                ('Issue_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Evaluation', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Archive', 'Archive')], default='Pending', max_length=20)),
                ('Reason', models.TextField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wsi_issues', to='reports.stockbook')),
            ],
        ),
    ]
