# Generated by Django 5.2.13 on 2026-05-09 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_summary_stockbook_summary_stockbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsireport',
            name='CerealType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wsireport',
            name='date_covered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wsireport',
            name='stockbooks',
            field=models.ManyToManyField(blank=True, related_name='wsi_reports', to='reports.stockbook'),
        ),
        migrations.AddField(
            model_name='wsrreport',
            name='CerealType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wsrreport',
            name='date_covered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wsrreport',
            name='stockbooks',
            field=models.ManyToManyField(blank=True, related_name='wsr_reports', to='reports.stockbook'),
        ),
        migrations.AlterField(
            model_name='wsireport',
            name='stockbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wsi_report_single', to='reports.stockbook'),
        ),
        migrations.AlterField(
            model_name='wsrreport',
            name='stockbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wsr_report_single', to='reports.stockbook'),
        ),
    ]
