# Generated by Django 6.0.2 on 2026-03-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_wsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsi',
            name='Name',
        ),
        migrations.AlterField(
            model_name='wrs',
            name='Report_id',
            field=models.ForeignKey(limit_choices_to={'WRS__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='wrs_receipts', to='reports.stockbook'),
        ),
        migrations.AlterField(
            model_name='wsi',
            name='Report_id',
            field=models.ForeignKey(limit_choices_to={'WSI__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='wsi_issues', to='reports.stockbook'),
        ),
    ]
