# Generated by Django 5.2.13 on 2026-05-09 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_wsireport_cerealtype_wsireport_date_covered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsireport',
            name='previous_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='reports.wsireport'),
        ),
        migrations.AddField(
            model_name='wsrreport',
            name='previous_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='reports.wsrreport'),
        ),
    ]
