# Generated by Django 5.2.13 on 2026-05-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_wsireport_previous_report_wsrreport_previous_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsireport',
            name='previous_report',
        ),
        migrations.RemoveField(
            model_name='wsrreport',
            name='previous_report',
        ),
    ]
