# Generated by Django 6.0.2 on 2026-03-29 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_wsi_name_alter_wrs_report_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrs',
            name='Created_at',
        ),
        migrations.RemoveField(
            model_name='wsi',
            name='Created_at',
        ),
        migrations.AddField(
            model_name='stockbook',
            name='Cond_I',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='stockbook',
            name='Cond_R',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('Summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('E_Bags', models.DecimalField(decimal_places=2, max_digits=10)),
                ('E_NKG', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_reports', to='reports.stockbook')),
            ],
        ),
    ]
