# Generated by Django 6.0.2 on 2026-03-29 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_wrs_created_at_remove_wsi_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='WRS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='reports.wrs'),
        ),
        migrations.AddField(
            model_name='summary',
            name='WSI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='reports.wsi'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='E_Bags',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='E_NKG',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
