# Generated by Django 6.0.2 on 2026-03-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_summary_wrs_summary_wsi_alter_summary_e_bags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='Report_id',
        ),
    ]
