# Generated by Django 6.0.2 on 2026-03-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_summary_report_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WRS',
            new_name='WSR',
        ),
        migrations.RenameField(
            model_name='stockbook',
            old_name='WRS',
            new_name='WSR',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='WRS',
            new_name='WSR',
        ),
    ]
