# Generated by Django 6.0.2 on 2026-03-29 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_rename_wrs_wsr_rename_wrs_stockbook_wsr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsr',
            name='Report_id',
            field=models.ForeignKey(limit_choices_to={'WSR__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='wsr_receipts', to='reports.stockbook'),
        ),
    ]
