# Generated by Django 6.0.3 on 2026-04-03 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('Audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_audited', models.DateField(auto_now_add=True)),
                ('Time_audited', models.TimeField(auto_now_add=True)),
                ('Module', models.CharField(blank=True, max_length=100, null=True)),
                ('Action', models.CharField(blank=True, max_length=255, null=True)),
                ('User_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='users.user')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'tbl_audit',
            },
        ),
    ]
